logging:
  config: classpath:logback-spring.xml
  path: /Users/kdj/Projects/external_env/gugudan/logs
  file: /Users/kdj/Projects/external_env/gugudan/logs/application.log
  level:
    d2: info
    org.springframework: info
    org.thymeleaf: info
    org.hibernate.SQL: info

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost:9092/~/Projects/external_env/gugudan/h2db/gugudan;MVCC=TRUE #각자에 맞게 수정
    username: sa
    password:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost:9092/~/Projects/external_env/gugudan/h2db/gugudan;MVCC=TRUE
      connection-test-query: SELECT 1
      username: sa
      password:
    platform: h2
  # jpa setting
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
  # devtools settings
  devtools:
    livereload:
      enabled: true
  # flywaydb setting
  flyway:
    enabled: false
    encoding: UTF-8
    check-location: true # 마이그레이션 스크립트 파일이 존재하는지 여부를 확인
    locations: classpath:db/migration/{vendor}/ # 마이그레이션 스크립트 위치
    baseline-version: 1 # 마이그레이션을 시작할 번호
    sql-migration-prefix: V
    url: jdbc:h2:tcp://localhost:9092/~/Projects/external_env/gugudan/h2db/gugudan;MVCC=TRUE  # Flyway 소유의 데이터소스를 생성하려고 하는 경우 사용
    user: sa # Flyway 소유의 데이터소스를 생성하려고 하는 경우 사용
    password: # Flyway 소유의 데이터소스를 생성하려고 하는 경우 사용
    gradle: # extend properties
      url: jdbc:h2:~/Projects/external_env/external_env/gugudan/h2db/gugudan;MVCC=TRUE
