logging:
  config: classpath:logback-spring.xml
  path: /Users/kdj/Projects/external_env/gugudan/logs
  file: /Users/kdj/Projects/external_env/gugudan/logs/application.log
  level:
    d2: info
    org.springframework: info
    org.thymeleaf: info
    org.hibernate.SQL: info

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost:9092/~/Projects/external_env/gugudan/h2db/gugudan;MVCC=TRUE #각자에 맞게 수정
    username: sa
    password:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost:9092/~/Projects/external_env/gugudan/h2db/gugudan;MVCC=TRUE
      connection-test-query: SELECT 1
      username: sa
      password:
    platform: h2
  # jpa setting
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
  # devtools settings
  devtools:
    livereload:
      enabled: true
