CREATE TABLE EXAM_HIST_MASTER (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  OPER_TYPE VARCHAR(255) NOT NULL,
  LEVEL VARCHAR(255) NOT NULL ,
  NAME VARCHAR(255) NOT NULL ,
  EXAM_COUNT INT NOT NULL ,
  SCORE INT NOT NULL ,
  TEST_TIME BIGINT NOT NULL ,
  CREATE_DATETIME DATETIME NOT NULL ,
  PRIMARY KEY (ID)
);

CREATE TABLE EXAM_HIST_DETAIL (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  QUESTION VARCHAR(255) NOT NULL ,
  ANSWER VARCHAR(255) NOT NULL,
  RESULT VARCHAR(255) NOT NULL ,
  EXAM_HIST_MASTER_ID BIGINT NOT NULL ,
  FOREIGN KEY (EXAM_HIST_MASTER_ID) REFERENCES EXAM_HIST_MASTER
)