ALTER TABLE EXAM_HIST_MASTER
    ADD COLUMN UPDATE_DATETIME DATETIME NOT NULL ;

ALTER TABLE EXAM_HIST_DETAIL
    ADD COLUMN CREATE_DATETIME DATETIME NOT NULL;

ALTER TABLE EXAM_HIST_DETAIL
    ADD COLUMN UPDATE_DATETIME DATETIME NOT NULL ;
